run:
  random_seed: 12345
  log_dir: ml_privacy_meter/logs/lcld_tabdpt/tabdpt
  time_log: true
  num_experiments: 1
audit:
  privacy_game: privacy_loss_model
  algorithm: RMIA
  num_ref_models: 1
  device: 0
  report_log: report_rmia
  batch_size: 5000
  n_jobs: -1
data:
  dataset: lcld
  data_dir: data/original
train:
  model_name: tabdpt
  device: 0
