run:
  random_seed: 12345
  log_dir: demo_purchase
  time_log: true
  num_experiments: 1
audit:
  privacy_game: privacy_loss_model
  algorithm: RMIA
  num_ref_models: 1
  device: cuda:0
  report_log: report_rmia
  batch_size: 5000
  data_size: 10000
  population_size: 10000
train:
  model_name: mlp
  device: cuda:0
  batch_size: 256
  optimizer: SGD
  learning_rate: 0.1
  weight_decay: 0
  epochs: 100
  hyperparameter_tuning: false
  tuning_n_trials: 30
  tuning_cv: 3
data:
  dataset: purchase100
  data_dir: data
