run:
  random_seed: 12345
  log_dir: ml_privacy_meter/logs/student_performance_mlp/mlp
  time_log: true
  num_experiments: 1
audit:
  privacy_game: privacy_loss_model
  algorithm: RMIA
  num_ref_models: 1
  device: cpu
  report_log: report_rmia
  batch_size: 5000
  n_jobs: -1
data:
  dataset: student_performance
  data_dir: data/original
train:
  model_name: mlp
  device: cpu
  batch_size: 256
  optimizer: SGD
  learning_rate: 0.01
  weight_decay: 0.0001
  epochs: 100
  hyperparameter_tuning: true
  tuning_n_trials: 30
  tuning_cv: 3
