run:
  random_seed: 12345
  log_dir: ml_privacy_meter/logs/surgery_tabnet/tabnet
  time_log: true
  num_experiments: 1
audit:
  privacy_game: privacy_loss_model
  algorithm: RMIA
  num_ref_models: 1
  device: cpu
  report_log: report_rmia
  batch_size: 5000
  n_jobs: -1
data:
  dataset: surgery
  data_dir: data/original
train:
  model_name: tabnet
  n_d: 32
  n_a: 32
  n_steps: 3
  gamma: 1.3
  batch_size: 256
  virtual_batch_size: 64
  max_epochs: 200
  patience: 15
  hyperparameter_tuning: true
  tuning_n_trials: 30
  tuning_cv: 3
